version: '3.1'

services:

  mongo:
    image: mongo:3.6.5
    restart: always
    expose:
    - 27017

  service_update_feeds:
    build: .
    volumes:
    - ./crontabs:/var/spool/cron/crontabs
    - ./:/var/task

    restart: ${RESTART}

    env_file: .env

    command: >
            bash -ic "
              while true
              do
              flask fetch_feeds
              sleep 10m
              done
              "

    tty: true

  service:

      build: .
      volumes:
      - ./:/var/task
      - ~/.aws/:/root/.aws:ro

      restart: ${RESTART}

      # expose in docker network
      expose:
      - ${SERVICE_PORT}

      # uplink port to host
      ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}

      env_file: .env

      #command: bash -c "echo 'i did nothing!'"
      command: >
            bash -ic "
              pip install -r requirements.txt
              flask run --host ${SERVICE_HOST} --port ${SERVICE_PORT}
              "

      tty: true
