version: '3.1'

services:

  mongo:
    image: mongo:3.6.5
    restart: always
    expose:
    - 27017

  service_update_feeds:
    image: janh/fltrbbl
    restart: always

    command: >
            bash -ic "
              /var/task/wait-for-it.sh --timeout=0 mongo:27017;
              while true
              do
              flask fetch_feeds
              sleep 10m
              done
              "

    environment:
        FLASK_APP: src:app

    tty: true

  service:
      image: janh/fltrbbl

      restart: always

      # uplink port to host
      ports:
      - 8080:8080

      command: FLASK_APP: gunicorn -w 4 --bind=0.0.0.0:8080 src:app
