"""empty message

Revision ID: 28dcfc8e9f3e
Revises: 39f197c52db4
Create Date: 2018-07-02 18:45:58.856662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28dcfc8e9f3e'
down_revision = '39f197c52db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('text_', sa.String(length=32768), nullable=True))
    op.drop_column('article', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('article', 'text_')
    # ### end Alembic commands ###
