"""empty message

Revision ID: 4567651e5d57
Revises: 7da63bcc501e
Create Date: 2018-07-02 22:08:43.963478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4567651e5d57'
down_revision = '7da63bcc501e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_column('feed', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('feed', 'title')
    # ### end Alembic commands ###
