"""empty message

Revision ID: d4533b882b2b
Revises: 28dcfc8e9f3e
Create Date: 2018-07-02 18:46:13.871847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4533b882b2b'
down_revision = '28dcfc8e9f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('text', sa.String(length=32768), nullable=True))
    op.drop_column('article', 'text_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('text_', sa.VARCHAR(length=32768), autoincrement=False, nullable=True))
    op.drop_column('article', 'text')
    # ### end Alembic commands ###
